### ISSUE TITLE
Is compatible with Rails 5.1.4?

### ISSUE THREAD

**Issue by pedrofurtado** [robinroestenburg/deferring#2]
@robinroestenburg Is compatible with Rails 5.1.4?

**Comment by robinroestenburg** [comment]
@pedrofurtado no, not yet. I am using `alias_method_chain` in some places, but that has been deprecated in Rails 5.1. I will work on a fix.

**Comment by pedrofurtado** [comment]
@robinroestenburg Thanks for feedback!

I tried to fix this deprecation in my fork, but I think I am doing it wrong. That is the comparison between my branch and the official of gem: 

https://github.com/robinroestenburg/deferring/compare/master...pedrofurtado:master

If you can help me about how to fix this deprecation or release a new version of the gem, it will help our team so much.

**Comment by robinroestenburg** [comment]
@pedrofurtado I've added the support for Rails 5.1 and pushed a new version (0.4.0) of the gem. Let me know if you run into anything.

**Comment by pedrofurtado** [comment]
@robinroestenburg Thanks, man! I will test on a application that I have in Rails 5.1.4 and I will send feedbacks here! Until the end of week I will give some feedback for you.

**Comment by pedrofurtado** [comment]
@robinroestenburg It works great in Rails 5.1.4, I've tested on my application here. Thanks!

**Comment by robinroestenburg** [comment]
@pedrofurtado thanks for the feedback 👍
