### ISSUE TITLE
Compatibility with Rails 6

### ISSUE THREAD

**Issue by pedrofurtado** [robinroestenburg/deferring#6]
@robinroestenburg  It's great to run the tests againts the Rails 6 (even it is still in beta), to turn it compatible with this major version :+1:

**Comment by robinroestenburg** [comment]
@pedrofurtado thanks for checking that, I have not had the time to play around with Rails 6 yet - when I do I will update the gem to make sure it is compatible.

**Comment by pedrofurtado** [comment]
@robinroestenburg Thanks for feedback! :beers: 

Rails 6 will be released in the next months, with a great evolution and new features. I can help you, if necessary, to make gem compatible with this version of Rails.

And thanks again for you work in this great library! :handshake:

**Comment by robinroestenburg** [comment]
@pedrofurtado version 0.6.0 is now available - you should be able to use that with Rails 6. If there are any issues, let me know - thanks!
